image: ubuntu:20.04

stages:
  - build_test
  - pages

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update
  - apt-get install -y --no-install-recommends software-properties-common
  - add-apt-repository ppa:ettusresearch/uhd
  - apt-get update
  - apt-get install -y --no-install-recommends cmake build-essential libboost-dev libuhd-dev uhd-host python3.9-venv python3.9-dev python3-wheel
  - python3.9 -m venv .venv
  - . .venv/bin/activate
  - pip install wheel

build_test:
  stage: build_test
  script:
    - pip install -e .
    - pip install -r requirements_tests.txt
    - cd uhd_wrapper
    - mkdir build && cd build
    - cmake -DINSTALL_SERVICE=OFF ..
    - make && make install
    - ctest -V
    - cd ../../
    - pytest .

pages:
  stage: pages
  script:
    - pip install -e .
    - pip install -r ../requirements_doc.txt
    - cd docs/source && make api && cd ../..
    - sphinx-build docs/source public
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
