image: ubuntu:20.04

before_script: 
  - export DEBIAN_FRONTEND=noninteractive
  - apt install software-properties-common
  - add-apt-repository ppa:ettusresearch/uhd
  - apt update
  - apt install -y cmake build-essential libuhd-dev libuhd4.1.0 uhd-host

stages:
  - build

job:
  stage: build
  script:
    - mkdir build && cd build
    - cmake ..
    - make