image: ubuntu:20.04

stages:
  - build_test

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update
  - apt-get install -y software-properties-common apt-utils
  - add-apt-repository ppa:ettusresearch/uhd
  - add-apt-repository ppa:deadsnakes/ppa
  - apt-get install -y cmake build-essential libboost-all-dev libuhd-dev libuhd4.1.0 uhd-host python3-pip python3.9

build_test:
  stage: build_test
  script:
    - pip install -e .
    - pip install -r requirements_tests.txt
    - cd usrp_uhd_wrapper
    - mkdir build && cd build
    - cmake ..
    - make
    - ctest -V
    - cd ..
    - python3 -m pytest tests/
