image: ubuntu:20.04

stages:
  - build_test

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get update
  - apt-get install -y software-properties-common apt-utils
  - add-apt-repository ppa:ettusresearch/uhd
  - apt-get install -y cmake build-essential libboost-all-dev libuhd-dev libuhd4.1.0 uhd-host python3-pip

build_test:
  stage: build_test
  script:
    - pip install -r requirements.txt
    - mkdir build && cd build
    - cmake ..
    - make
    - ctest -V
    - cd ..
    - python -m pytest tests/python/