image: ubuntu:20.04

before_script: 
  - export DEBIAN_FRONTEND=noninteractive
  - apt update
  - apt install -y cmake build-essential

stages:
  - build

job:
  stage: build
  script:
    - mkdir build && cd build
    - cmake ..
    - make